### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by robkovacs** [fantasticole/ScriptEd-Jeopardy#11]
Press S to display scoreboard. Scoreboard will pull each team's name and current score from gameData.teams.

**Comment by robkovacs** [comment]
See issue #8.

**Comment by fantasticole** [comment]
Scoreboard being populated with data at the creation of the teams. Needs to be updated as team scores update.

**Comment by robkovacs** [comment]
The PR from a few mins ago fixes this.
