### ISSUE TITLE
Make sure the same avatar doesn't get picked for more than one team

### ISSUE THREAD

**Issue by robkovacs** [fantasticole/ScriptEd-Jeopardy#22]

**Comment by fantasticole** [comment]
When I created the randomize function, I had it splice the chosen element out of the array. I never got any duplicates, but I noticed that you removed that part from the code. Did it not work for you?

**Comment by robkovacs** [comment]
I see. I didn't realize that was supposed to do more than just pick a
random element, so that's the only reason I took it out.
